# Generated by Django 5.0.3 on 2024-03-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('remind_date', models.DateField()),
                ('remind_time', models.TimeField()),
            ],
        ),
    ]
